version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hr
      - MYSQL_USER=hruser
      - MYSQL_PASSWORD=hrpassword
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  # ใช้ nginx เป็น load balancer
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    # ใช้ config แบบ inline แทนการ mount ไฟล์
    command: |
      /bin/sh -c "echo '
      upstream api {
          server api:3001;
      }
      server {
          listen 80;
          server_name localhost;
          client_max_body_size 10M;
          
          # CORS configuration จัดการโดย NestJS แล้ว ไม่ต้องตั้งค่าที่ Nginx
          
          location / {
              proxy_pass http://api;
              proxy_set_header Host \$$host;
              proxy_set_header X-Real-IP \$$remote_addr;
              proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto \$$scheme;
              proxy_connect_timeout 300s;
              proxy_send_timeout 300s;
              proxy_read_timeout 300s;
          }
      }
      ' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - api

  api:
    build: .
    # ไม่ต้องเปิด port ออกมาภายนอก ให้ nginx เป็นตัวจัดการ
    # ports:
    #   - "5000-5010:3001"
    depends_on:
      - mysql
    environment:
      - PORT=3001
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=hruser
      - DATABASE_PASSWORD=hrpassword
      - DATABASE_NAME=hr
      - DATABASE_SYNCHRONIZE=true
      - DATABASE_LOGGING=true
      - JWT_SECRET=madeeonfire
    restart: always
    # รอให้ MySQL พร้อมใช้งานก่อน
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: